case TRAP_UPDATESCREEN: SCR_UpdateScreen(); return 0;
case TRAP_S_STARTLOCALSOUND: S_StartLocalSound(args[1], args[2]); return 0;
case TRAP_S_REGISTERSOUND: return S_RegisterSound(VMA(1), args[2]);
case TRAP_R_REGISTERMODEL: return re.RegisterModel(VMA(1));
case TRAP_R_REGISTERSKIN: return re.RegisterSkin(VMA(1));
case TRAP_R_REGISTERSHADER: return re.RegisterShader(VMA(1));
case TRAP_R_REGISTERSHADERNOMIP: return re.RegisterShaderNoMip(VMA(1));
case TRAP_R_CLEARSCENE: re.ClearScene(); return 0;
case TRAP_R_ADDREFENTITYTOSCENE: re.AddRefEntityToScene(VMA(1), qfalse); return 0;
case TRAP_R_ADDPOLYTOSCENE: re.AddPolyToScene(args[1], args[2], VMA(3), 1); return 0;
case TRAP_R_ADDLIGHTTOSCENE: re.AddLightToScene(VMA(1), VMF(2), VMF(3), VMF(4), VMF(5)); return 0;
case TRAP_R_ADDLINEARLIGHTTOSCENE: re.AddLinearLightToScene(VMA(1), VMA(2), VMF(3), VMF(4), VMF(5), VMF(6)); return 0;
case TRAP_R_RENDERSCENE: re.RenderScene(VMA(1)); return 0;
case TRAP_R_SETCOLOR: re.SetColor(VMA(1)); return 0;
case TRAP_R_DRAWSTRETCHPIC: re.DrawStretchPic(VMF(1), VMF(2), VMF(3), VMF(4), VMF(5), VMF(6), VMF(7), VMF(8), args[9]); return 0;
case TRAP_R_LERPTAG: return re.LerpTag(VMA(1), args[2], args[3], args[4], VMF(5), VMA(6));
case TRAP_GETGLCONFIG: CL_GetGlconfig(VMA(1)); return 0;
case TRAP_KEY_GETCATCHER: return Key_GetCatcher();
case TRAP_R_REMAP_SHADER: re.RemapShader(VMA(1), VMA(2), VMA(3)); return 0;