case TRAP_MEMSET: Com_Memset(VMA(1), args[2], args[3]); return args[1];
case TRAP_MEMCPY: Com_Memcpy(VMA(1), VMA(2), args[3]); return args[1];
case TRAP_STRNCPY: Q_strncpy(VMA(1), VMA(2), args[3]); return args[1];
case TRAP_SIN: return FloatAsInt(sin(VMF(1)));
case TRAP_COS: return FloatAsInt(cos(VMF(1)));
case TRAP_ACOS: return FloatAsInt(Q_acos(VMF(1)));
case TRAP_ATAN2: return FloatAsInt(atan2(VMF(1), VMF(2)));
case TRAP_SQRT: return FloatAsInt(sqrt(VMF(1)));
case TRAP_PRINT: Com_Printf("%s", (const char*)VMA(1)); return 0;
case TRAP_ERROR: Com_Error(ERR_DROP, "%s", (const char*)VMA(1)); return 0;
case TRAP_MILLISECONDS: return Sys_Milliseconds();
case TRAP_CVAR_REGISTER: Cvar_Register(VMA(1), VMA(2), VMA(3), args[4]); return 0;
case TRAP_CVAR_UPDATE: Cvar_Update(VMA(1), args[2]); return 0;
case TRAP_CVAR_SET: Cvar_Set(VMA(1), VMA(2)); return 0;
case TRAP_CVAR_SETVALUE: Cvar_SetValue(VMA(1), VMF(2)); return 0;
case TRAP_ARGC: return Cmd_Argc();
case TRAP_ARGV: Cmd_ArgvBuffer(args[1], VMA(2), args[3]); return 0;
case TRAP_ARGS: Cmd_ArgsBuffer(VMA(1), args[2]); return 0;
case TRAP_FS_OPEN: return FS_VM_OpenFile(VMA(1), VMA(2), args[3]);
case TRAP_FS_READ: FS_VM_ReadFile(VMA(1), args[2], args[3]); return 0;
case TRAP_FS_WRITE: FS_VM_WriteFile(VMA(1), args[2], args[3]); return 0;
case TRAP_FS_CLOSE: FS_VM_CloseFile(args[1]); return 0;
case TRAP_FS_LIST: return FS_GetFileList(VMA(1), VMA(2), VMA(3), args[4]);
case TRAP_CMD: Cbuf_ExecuteText(args[1], VMA(2)); return 0;
case TRAP_REAL_TIME: return Com_RealTime(VMA(1));
case UI_SYSTEM: Sys_Cmd((const char*)VMA(1)); return 0;